version: 2.1
working_directory: ~/
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: 16.0.0
      - run: cd client && npm install
      - run: cd client && npm run lint
      - run: cd client && npm test
workflows:
  deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: $HEROKU_CI_APP_NAME
          force: true
          requires:
            - build
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          force: true
          requires:
            - build
          filters:
            branches:
              only: master
